inputs:
  data: datasets/skimmed/skimmed_LHC22o__k0s.parquet
  mc: datasets/skimmed/skimmed_LHC24g5__k0s.parquet

fit:
  signal_data:

mother_mass_var_name: fMassK0
mother_pt_var_name: fPt
variables_to_plot: [fNSigmaTpcPosPi, fNSigmaTpcNegPi, fNSigmaTofPosPi, fNSigmaTofNegPi]
dau_pt_var_names: [fPtPos, fPtNeg, fPtPos, fPtNeg] # relative to the variables_to_plot
mass_range: [0.45, 0.55]
pt_bins: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.5, 2.0, 4.0]

output:
  dir: distributions/k0s/pp