inputs:
  data: datasets/LHC22o_pass7/Train306507/Tree_LHC22o_pass7_K0s_Lambda.root
  mc: datasets/LHC24g5/Train308276/Tree_LHC24g5_K0s_Lambda.root
  tree_name: O2pidv0s

n_workers: 10

cutset: configs/cutset_k0s.yml

flag:
  name: fCandFlag
  values: [1]

outputs:
  dir: datasets/skimmed
  suffix: _k0s