histofile: "/home/mdicosta/hf_pid_studies/analysis/selections_pbpb.root"

trees:
-   treefile: '/data/shared/hf_pid_studies_pbpb/Data/Train301809/AO2D_LHC23zzh_pass4_small_casc.root'
    datasetname: "casc_pbpb_data"
    foldername: 'O2pidcascades'
    masscol: "fMassOmega"
    histocfg: [100,1.5,1.8]
    selections: "(fMassXi < 1.30 or fMassXi > 1.35) and fCascCosPA > 0.9999 and fDCAV0daughters < 0.05 and fDCAv0topv > 0.02 and fDCAv0topv < 1"
    outfile: '../seldatasets/Tree_LHC23zzh_pass4_small_Casc_sel_pbpbdata.parquet'

-   treefile: '/data/shared/hf_pid_studies_pbpb/Data/Train301810/AO2D_LHC23zzh_pass4_small_v0s.root'
    subsets:
    -   datasetname: "k0_pbpb_data"
        foldername: 'O2pidv0s'
        masscol: "fMassK0"
        histocfg: [100,0.4,0.6]
        selections: "fCpa > 0.9999 and (fMassLambda < 1.114 or fMassLambda > 1.117) and (fMassAntiLambda < 1.114 or fMassAntiLambda > 1.117) and fQtArm >  0.12"
        outfile: '../seldatasets/Tree_LHC23zzh_pass4_small_K0s_sel_pbpbdata.parquet'
    -   datasetname: "lambda_pbpb_data"
        foldername: 'O2pidv0s'
        masscol: "fMassLambda"
        histocfg: [100,1.0,1.3]
        selections: "((fMassLambda > 1.0 and fMassLambda < 1.3) or (fMassAntiLambda > 1.0 and fMassAntiLambda < 1.3)) and fCpa > 0.9999 and (fMassK0 < 0.470 or fMassK0 > 0.525) and fQtArm < 0.12 and fRadius > 0.2"
        outfile: '../seldatasets/Tree_LHC23zzh_pass4_small_Lambda_sel_pbpbdata.parquet'

-   treefile: '/data/shared/hf_pid_studies_pbpb/MC/Train303905/AO2D_LHC24g2_small_casc.root'
    datasetname: "casc_pbpb_mc"
    foldername: 'O2pidcascades'
    masscol: "fMassOmega"
    histocfg: [100,1.5,1.8]
    selections: "fCandFlag == 3 or fCandFlag == -3"
    outfile: '../seldatasets/Tree_LHC24g2_small_Casc_sel_pbpbmc.parquet'

-   treefile: '/data/shared/hf_pid_studies_pbpb/MC/Train303621/AO2D_LHC24g2_small.root'
    subsets:
    -   datasetname: "k0_pbpb_mc"
        foldername: 'O2pidv0s'
        masscol: "fMassK0"
        histocfg: [100,0.4,0.6]
        selections: "fCandFlag == 1"
        outfile: '../seldatasets/Tree_LHC24g2_small_K0s_sel_pbpbmc.parquet'
    -   datasetname: "lambda_pbpb_mc"
        foldername: 'O2pidv0s'
        masscol: "fMassLambda"
        histocfg: [100,1.0,1.3]
        selections: "fCandFlag == 2 or fCandFlag == -2"
        outfile: '../seldatasets/Tree_LHC24g2_small_Lambda_sel_pbpbmc.parquet'