histofile: "/home/mdicosta/hf_pid_studies/seldatasets/pbpb/mc/selections_pbpb.root"

trees:

##### Omega MC
-   treefile: '/data/shared/hf_pid_studies_pbpb/casc/MC/Train306408/LHC24g2_medium_casc.parquet'
    # datasetname: "casc_pbpb_data"
    masscol: "fMassOmega"
    histocfg: [100,1.5,1.8]
    # selections: ""
    outfile: '../seldatasets/pbpb/mc/LHC24g2_medium_casc.parquet'

##### Lambda MC
-   treefile: '/data/shared/hf_pid_studies_pbpb/v0s/MC/Train306702/LHC24g2_medium.parquet'
    # datasetname: "casc_pbpb_data"
    masscol: "fMassLambda"
    histocfg: [100,1.0,1.3]
    selections: "fCandFlag == 2"
    outfile: '../seldatasets/pbpb/mc/LHC24g2_medium_lambda.parquet'

##### AntiLambda MC
-   treefile: '/data/shared/hf_pid_studies_pbpb/v0s/MC/Train306702/LHC24g2_medium.parquet'
    # datasetname: "casc_pbpb_data"
    masscol: "fMassAntiLambda"
    histocfg: [100,1.0,1.3]
    selections: "fCandFlag == -2"
    outfile: '../seldatasets/pbpb/mc/LHC24g2_medium_antilambda.parquet'

##### K0s MC
-   treefile: '/data/shared/hf_pid_studies_pbpb/v0s/MC/Train306702/LHC24g2_medium.parquet'
    # datasetname: "casc_pbpb_data"
    masscol: "fMassK0"
    histocfg: [100,0.4,0.6]
    selections: "fCandFlag == 1"
    outfile: '../seldatasets/pbpb/mc/LHC24g2_medium_k0s.parquet'